safe: true
pygments: true
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
author :
  name : Sebastian Schmidt
  email : publicarray@icloud.com
  github : publicarray
production_url : http://publicarray.github.io
